"""
Internal Metrics & Map-Data Endpoints
--------------------------------------
Debug / analytics routes that are completely isolated from the public API.
Mounted under /internal — the frontend never touches these.
"""

from fastapi import APIRouter, Query
from pymongo.errors import PyMongoError

from app.services.metrics import get_metrics_summary, get_comparison_metrics
from app.services.branches import BRANCHES
from app.db import orders

router = APIRouter()


@router.get("/metrics")
def metrics_summary():
    """
    GET /internal/metrics

    Returns aggregate delivery metrics:
        total_orders, avg_distance, avg_delivery_time, orders_per_branch
    """
    summary = get_metrics_summary()
    return {
        "total_orders": summary["total_orders"],
        "avg_distance": summary["average_distance"],
        "avg_delivery_time": summary["average_delivery_time"],
        "orders_per_branch": summary["orders_per_branch"],
    }


@router.get("/metrics/comparison")
def metrics_comparison():
    """
    GET /internal/metrics/comparison

    Side-by-side single-kitchen vs multi-branch analysis:
        multi_branch_avg_distance, single_kitchen_avg_distance,
        improvement_percentage, etc.
    """
    return get_comparison_metrics()


@router.get("/map-data")
def map_data(limit: int = Query(default=2000, ge=1, le=10000)):
    """
    GET /internal/map-data

    Returns branch metadata and simulated order positions for the
    Leaflet visualisation.  Only orders with is_simulated=True are
    included so real customer data is never exposed here.

    Response shape:
    {
        "branches": [{"id", "name", "lat", "lng"}, ...],
        "orders":   [{"lat", "lng", "branch_id", "distance_km",
                      "estimated_delivery_time"}, ...]
    }
    """
    branch_list = [
        {"id": b["id"], "name": b["name"], "lat": b["lat"], "lng": b["lng"]}
        for b in BRANCHES
    ]

    projection = {
        "_id": 0,
        "user_lat": 1,
        "user_lng": 1,
        "branch_id": 1,
        "distance_km": 1,
        "estimated_delivery_time": 1,
    }
    order_list = []
    try:
        cursor = (
            orders
            .find({"is_simulated": True}, projection)
            .limit(limit)
        )

        for doc in cursor:
            order_list.append({
                "lat":                    doc.get("user_lat"),
                "lng":                    doc.get("user_lng"),
                "branch_id":              doc.get("branch_id", "unknown"),
                "distance_km":            round(doc.get("distance_km", 0), 2),
                "estimated_delivery_time": doc.get("estimated_delivery_time", "N/A"),
            })
    except PyMongoError:
        order_list = []

    return {
        "branches": branch_list,
        "orders":   order_list,
        "count":    len(order_list),
    }

@router.get("/optimized-branches")
def get_optimized_branches():
    """
    GET /internal/optimized-branches
    Returns the optimized branch locations generated by the clustering script.
    """
    from app.db import db
    try:
        cursor = db["optimized_branches"].find({}, {"_id": 0})
        return list(cursor)
    except PyMongoError:
        return []
