DEFAULT_MENU_ITEMS = [
    {
        "id": "butter-chicken-bowl",
        "name": "Butter Chicken Bowl",
        "category": "Bestsellers",
        "price": 289,
        "rating": 4.7,
        "eta": "25-30 mins",
        "is_veg": False,
        "description": "Creamy tomato gravy with grilled chicken, jeera rice, and onion salad.",
        "accent": "from-orange-400 via-amber-300 to-rose-200",
        "is_available": True,
    },
    {
        "id": "hyderabadi-biryani",
        "name": "Hyderabadi Chicken Biryani",
        "category": "Biryani",
        "price": 329,
        "rating": 4.8,
        "eta": "30-35 mins",
        "is_veg": False,
        "description": "Dum-style biryani layered with saffron rice, masala chicken, and raita.",
        "accent": "from-amber-500 via-orange-300 to-yellow-100",
        "is_available": True,
    },
    {
        "id": "paneer-tikka-roll",
        "name": "Paneer Tikka Roll",
        "category": "Rolls",
        "price": 199,
        "rating": 4.5,
        "eta": "20-25 mins",
        "is_veg": True,
        "description": "Charred paneer, mint mayo, pickled onions, and flaky roomali wrap.",
        "accent": "from-emerald-500 via-lime-300 to-stone-100",
        "is_available": True,
    },
    {
        "id": "smoky-kebab-roll",
        "name": "Smoky Kebab Roll",
        "category": "Rolls",
        "price": 229,
        "rating": 4.6,
        "eta": "20-25 mins",
        "is_veg": False,
        "description": "Chicken seekh kebab roll with garlic sauce and crunchy onions.",
        "accent": "from-red-500 via-orange-300 to-zinc-100",
        "is_available": True,
    },
    {
        "id": "paneer-makhani-bowl",
        "name": "Paneer Makhani Rice Bowl",
        "category": "Bowls",
        "price": 249,
        "rating": 4.4,
        "eta": "25-30 mins",
        "is_veg": True,
        "description": "Rich makhani paneer with basmati rice and cucumber crunch.",
        "accent": "from-rose-400 via-orange-200 to-yellow-100",
        "is_available": True,
    },
    {
        "id": "peri-peri-fries",
        "name": "Peri Peri Loaded Fries",
        "category": "Bestsellers",
        "price": 169,
        "rating": 4.3,
        "eta": "15-20 mins",
        "is_veg": True,
        "description": "Crispy fries with peri peri dust, cheese drizzle, and spring onions.",
        "accent": "from-orange-500 via-red-300 to-yellow-100",
        "is_available": True,
    },
    {
        "id": "gulab-jamun-cheesecake",
        "name": "Gulab Jamun Cheesecake",
        "category": "Desserts",
        "price": 159,
        "rating": 4.7,
        "eta": "10-15 mins",
        "is_veg": True,
        "description": "Baked cheesecake topped with warm gulab jamun crumble and syrup glaze.",
        "accent": "from-pink-400 via-rose-200 to-orange-100",
        "is_available": True,
    },
    {
        "id": "alfredo-pasta",
        "name": "Creamy Alfredo Pasta",
        "category": "Italian",
        "price": 279,
        "rating": 4.4,
        "eta": "25-30 mins",
        "is_veg": True,
        "description": "Silky white sauce pasta with herbs, sauteed mushrooms, and garlic toast crumbs.",
        "accent": "from-yellow-200 via-orange-100 to-stone-100",
        "is_available": True,
    },
    {
        "id": "arrabbiata-penne",
        "name": "Arrabbiata Penne",
        "category": "Italian",
        "price": 259,
        "rating": 4.3,
        "eta": "25-30 mins",
        "is_veg": True,
        "description": "Penne tossed in spicy tomato sauce with olives, basil, and parmesan notes.",
        "accent": "from-red-500 via-orange-300 to-amber-100",
        "is_available": True,
    },
    {
        "id": "veg-hakka-noodles",
        "name": "Veg Hakka Noodles",
        "category": "Chinese",
        "price": 219,
        "rating": 4.5,
        "eta": "20-25 mins",
        "is_veg": True,
        "description": "Wok-tossed noodles with crunchy vegetables, soy glaze, and spring onion finish.",
        "accent": "from-amber-400 via-lime-200 to-stone-100",
        "is_available": True,
    },
    {
        "id": "chilli-chicken-rice",
        "name": "Chilli Chicken Rice Bowl",
        "category": "Chinese",
        "price": 289,
        "rating": 4.6,
        "eta": "25-30 mins",
        "is_veg": False,
        "description": "Spicy chilli chicken with fried rice, peppers, and glossy Indo-Chinese sauce.",
        "accent": "from-red-600 via-orange-400 to-yellow-100",
        "is_available": True,
    },
    {
        "id": "korean-fried-chicken",
        "name": "Korean Fried Chicken",
        "category": "Korean",
        "price": 319,
        "rating": 4.7,
        "eta": "25-30 mins",
        "is_veg": False,
        "description": "Crispy fried chicken coated in gochujang glaze with sesame and scallion crunch.",
        "accent": "from-rose-600 via-orange-300 to-stone-100",
        "is_available": True,
    },
    {
        "id": "kimchi-rice-bowl",
        "name": "Kimchi Rice Bowl",
        "category": "Korean",
        "price": 249,
        "rating": 4.4,
        "eta": "20-25 mins",
        "is_veg": True,
        "description": "Steamed rice topped with kimchi, sauteed vegetables, sesame, and spicy mayo drizzle.",
        "accent": "from-red-500 via-pink-200 to-orange-100",
        "is_available": True,
    },
    {
        "id": "spicy-miso-ramen",
        "name": "Spicy Miso Ramen",
        "category": "Ramen",
        "price": 329,
        "rating": 4.8,
        "eta": "30-35 mins",
        "is_veg": False,
        "description": "Rich miso broth with noodles, chicken slices, egg, corn, and chili oil finish.",
        "accent": "from-orange-500 via-yellow-200 to-stone-100",
        "is_available": True,
    },
    {
        "id": "veg-korean-ramen",
        "name": "Veg Korean Ramen",
        "category": "Ramen",
        "price": 289,
        "rating": 4.5,
        "eta": "25-30 mins",
        "is_veg": True,
        "description": "Fiery ramen broth with noodles, tofu, mushrooms, bok choy, and sesame garnish.",
        "accent": "from-red-500 via-orange-200 to-yellow-100",
        "is_available": True,
    },
    {
        "id": "cold-coffee",
        "name": "Hazelnut Cold Coffee",
        "category": "Beverages",
        "price": 129,
        "rating": 4.2,
        "eta": "10-15 mins",
        "is_veg": True,
        "description": "Chilled coffee shake with hazelnut notes and whipped cream.",
        "accent": "from-stone-600 via-amber-500 to-stone-100",
        "is_available": True,
    },
]
